// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xpksavyevbijnrbgjepm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inhwa3NhdnlldmJpam5yYmdqZXBtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1NzczMTMsImV4cCI6MjA2ODE1MzMxM30.TQzxTjEiJrIWAqq23lGRlb3QHRN4hb1VlDLqnU8DIRc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});